######################################################################
# Automatically generated by qmake (3.0) lun. avr. 21 22:59:24 2014
######################################################################

TEMPLATE = app
TARGET = Serveur
INCLUDEPATH += . header

QT += widgets
QT += network
QT += sql

unix:OBJECTS_DIR = objs/

# Input
HEADERS += header/serveur.hh

SOURCES += srcs/serveur.cpp \
           srcs/main.cpp
